[package]
name = "crates_io_og_image"
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "OpenGraph image generation for crates.io"

[lints]
workspace = true

[dependencies]
anyhow = "=1.0.98"
crates_io_env_vars = { path = "../crates_io_env_vars" }
tempfile = "=3.20.0"
tokio = { version = "=1.45.1", features = ["process", "fs"] }

[dev-dependencies]
tokio = { version = "=1.45.1", features = ["macros", "rt-multi-thread"] }
